#!/bin/bash

IMG_BASE="/var/lib/libvirt/images"

if [ -z "$1" ]; then
    echo "I need the label"
    exit 1
fi

label=$1

if [ ! -e "${IMG_BASE}/${label}.qcow2.backup" ]; then
    cp "${IMG_BASE}/${label}.qcow2" "${IMG_BASE}/${label}.qcow2.backup"
fi

exit 0
